from tkinter import *
root= Tk()
root.title('Scientific Calculator')
root.geometry('730x305')

frame = Frame(root, height="810", width="500", bg="gray24")

#change to area for result later
Button(frame,height="3", width='60',bg="white", fg="gray24", text="result").grid(row=0, column=0,rowspan=2,columnspan=7)

b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="sin").grid(row=2, column=0)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="cos").grid(row=2, column=1)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="tan").grid(row=2, column=2)
b=Button(frame, height='2', width='7',bg="red", fg="white", text="5").grid(row=2, column=3)
b=Button(frame, height='2', width='7',bg="red", fg="white", text="5").grid(row=2, column=4)
b=Button(frame, height='2', width='7',bg="red", fg="white", text="5").grid(row=2, column=5)
b=Button(frame, height='2', width='7',bg="red", fg="white", text="Clr").grid(row=2, column=6)
b=Button(frame, height='2', width='7',bg="red", fg="white", text="AC").grid(row=2, column=7)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=3, column=0)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=3, column=1)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="5").grid(row=3, column=2)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="7").grid(row=3, column=3)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="8").grid(row=3, column=4)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="9").grid(row=3, column=5)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="pi").grid(row=3, column=6)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="mod").grid(row=3, column=7)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=4, column=0)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=4, column=1)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="5").grid(row=4, column=2)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="4").grid(row=4, column=3)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="5").grid(row=4, column=4)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="6").grid(row=4, column=5)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="x").grid(row=4, column=6)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="/").grid(row=4, column=7)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=5, column=0)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=5, column=1)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="5").grid(row=5, column=2)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="1").grid(row=5, column=3)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="2").grid(row=5, column=4)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="3").grid(row=5, column=5)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="+").grid(row=5, column=6)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="-").grid(row=5, column=7)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=6, column=0)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="8").grid(row=6, column=1)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="5").grid(row=6, column=2)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text=".").grid(row=6, column=3)
b=Button(frame, height='2', width='7',bg="black", fg="white", text="0").grid(row=6, column=4)
b=Button(frame, height='2', width='7',bg="gray24", fg="white", text="=").grid(row=6, column=5)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text="(").grid(row=6, column=6)
b=Button(frame, height='2', width='7',bg="blue", fg="white", text=")").grid(row=6, column=7)


frame.pack(fill=BOTH)


root.mainloop()
